include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/python-tests.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/test/check-merge-compatibility.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/python-module-release.yml"


Run python v3.9 tests:
  image: "registry.hpc.ut.ee/mirror/library/python:3.9"
  extends: .Run tests template

Run python v3.10 tests:
  image: "registry.hpc.ut.ee/mirror/library/python:3.10"
  extends: .Run tests template

Run python v3.11 tests:
  image: "registry.hpc.ut.ee/mirror/library/python:3.11"
  extends: .Run tests template

Run python v3.12 tests:
  image: "registry.hpc.ut.ee/mirror/library/python:3.12"
  extends: .Run tests template

Run python v3.13 tests:
  image: "registry.hpc.ut.ee/mirror/library/python:3.13"
  extends: .Run tests template


Run linters:
  image: registry.hpc.ut.ee/mirror/library/python:3.11-bullseye
  stage: test
  interruptible: true
  rules:
    # Skip tests if said so
    - if: '$SKIP_TESTS == "true" || $SKIP_TESTS == "yes"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    # If tagged release
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
    # If event is related to a created merge request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - pip install pre-commit
    - pre-commit run --all
